language: ruby
before_script:
- psql -c 'create database show_caster_test;' -U postgres
- psql -c "CREATE USER sesame WITH PASSWORD 'bar';"
- psql -c "ALTER ROLE sesame WITH SUPERUSER;"
rvm:
- 2.2.7
branches:
  only:
  - master
services:
- postgresql
- redis-server
addons:
  chrome: stable
