language: ruby
rvm:
 - 2.2.7
# safelist
branches:
  only:
    - master
services:
  - postgresql
before_script:
  - psql -c 'create database show_caster_test;' -U postgres
  - psql -c "CREATE USER sesame WITH PASSWORD 'bar';"
  - psql -c "ALTER ROLE sesame WITH SUPERUSER;"
addons:
  chrome: stable
