language: ruby
before_script:
  - bundle exec sidekiq -d -r ./spec/dummy_app/app.rb -L /tmp/sidekiq.log
  - sleep 1
rvm:
 - 2.2.7
# safelist
branches:
  only:
    - master
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database show_caster_test;' -U postgres
  - psql -c "CREATE USER sesame WITH PASSWORD 'bar';"
  - psql -c "ALTER ROLE sesame WITH SUPERUSER;"
addons:
  chrome: stable
