language: ruby
before_script:
  - psql -c 'create database show_caster_test;' -U postgres
  - psql -c "CREATE USER sesame WITH PASSWORD 'bar';"
  - psql -c "ALTER ROLE sesame WITH SUPERUSER;"
rvm:
  - 2.4.1
branches:
  only:
    - master
services:
  - postgresql
  - redis-server
addons:
  chrome: stable
