version: '3.4'


services:
  redis:
    image: redis:5.0.7

  database:
    image: "postgres:12.1"
    ports:
      - "5432"
    restart: always
    env_file:
      - env/database.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - bundle_cache
      - redis
      - chrome
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/bundle_cache
      - node_modules:/app/node_modules
    env_file:
      - env/application.env
      - env/sidekiq.env
      - env/database.env
    stdin_open: true
    tty: true

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - database
      - redis
      - bundle_cache
    volumes:
      - .:/app
      - bundle_cache:/bundle_cache
    env_file:
      - env/application.env
      - env/sidekiq.env
      - env/database.env
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

  bundle_cache:
    image: busybox
    volumes:
      - bundle_cache:/bundle_cache

  chrome:
    image: selenium/standalone-chrome
    # logging:
    #   driver: "none"
    ports:
      - "4444:4444"
      - "5900:5900"

volumes:
  bundle_cache:
  db_data:
  node_modules:
