version: '3.4'

services:
  redis:
    image: redis:5.0.7
  database:
    image: "postgres:12.1"
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: sesame
      POSTGRES_DB: matwo
    env_file:
      - .env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/bundle_cache
      - node_modules:/app/node_modules
    env_file:
      - .env
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - database
      - redis
    volumes:
      - .:/app
      - bundle_cache:/bundle_cache
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh
  bundle_cache:
    image: busybox
    volumes:
      - bundle_cache:/bundle_cache
volumes:
  bundle_cache:
  db_data:
  node_modules:
