FROM ruby:2.4.1
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
RUN mkdir /sesames
WORKDIR /sesames
COPY Gemfile /sesames/Gemfile
COPY Gemfile.lock /sesames/Gemfile.lock
RUN bundle install
COPY . /sesames

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]