# PostgreSQL. Versions 9.1 and up are supported.
#
default: &default
  host: database # and then database ! TODO
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 2) %>
  username: <%= ENV.fetch('SHOW_CASTER_DATABASE_USERNAME') %>
  timeout: 5000
  port: <%= ENV.fetch('SHOW_CASTER_PORT') %>
  database: <%= ENV.fetch('SHOW_CASTER_DATABASE_NAME') %>

development:
  <<: *default
  password: matwo

test:
  <<: *default
  database: showcaster_test
  password: <%= ENV.fetch('POSTGRES_PASSWORD')%>
production:
  <<: *default
  database: show_caster
  host: <%= ENV.fetch('SHOW_CASTER_HOST') %>
  port: <%= ENV.fetch('SHOW_CASTER_PORT') %>
  password: <%= ENV.fetch('SHOW_CASTER_DATABASE_PASSWORD') %>

