---
:verbose: true
:concurrency: 4
:SHOW_CASTER_DATABASE_PASSWORD: <%= ENV['SHOW_CASTER_DATABASE_PASSWORD'] %>
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - [critical, 2]
  - default
  - low

production:
  :concurrency: 10
